name: data operations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.dev ];
          then pip install -r requirements.dev;
          fi
      - name: Run tests
        run: |
          python -m pytest -v
          python -m coverage run -m pytest
          coverage report
          coverage html
      - name: Achive code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: htmlcov